# Generated by Django 4.1.7 on 2023-04-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_filter',
            field=models.TextField(default='unisex', max_length=30),
        ),
    ]
